### ISSUE TITLE
Hardcoded system path in library headers

### ISSUE THREAD

**Issue by ferdnyc** [OpenPrinting/cpdb-libs#9]
Continuing from OpenPrinting/cpdb-backend-cups#15...

Currently, the path `/usr/share/print-backends`  is hardcoded into the library as the `CPDB_DBUS_DIR`, on line 23 of `cpdb-frontend.h`:

https://github.com/OpenPrinting/cpdb-libs/blob/f30fd6074a8a72a8068c35e7a214d1836a5570ca/cpdb/cpdb-frontend.h#L21-L25

I guarantee that's going to make at least the NixOS people unhappy, for starters... and really, any system path should be based on the install `${prefix}` and other paths configured dynamically by autoconf. (That's the _purpose_ of autoconf, after all.)

In turn, the value determined for `CPDB_DBUS_DIR` in a `cpdb-libs` build can be included in its pkg-config data as an additional variable. (It can actually just be hardcoded to `${datadir}/print-backends` there, allowing the autoconf `${prefix}` and other path variables to control its location.)

That will allow dependent packages to know where a specific installed build of the library expects to find its backend data files, so that the consumers don't have to hardcode any paths either.

**Comment by tillkamppeter** [comment]
Fixed in commit 578ead2ac0

Thanks for the bug report.
